name: lakasanepal
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41647098725661635
title: Lakasa Nepal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-63005021-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.28456320241093636
  lightness: 0.9551012688316405
  saturation: 0.4022041445132345
  rhythmicContrast: 0.2554521874990314
purpose: []
